import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import dynamic from 'next/dynamic';
import { useCallback, useState } from 'react';
import { Content, OnChangeStatus } from 'vanilla-jsoneditor';

const JSONEditorReact = dynamic(() => import('@/components/JSONEditorReact'), { ssr: false });

const initialContent = { 
  "hello": "world",
  "count": 1,
  "foo": [
    "bar",
    "car",
  ],
};

export default function Home() {
  const [jsonContent, setJsonContent] = useState<Content>({ json: initialContent });
  const handler = useCallback((content: Content, previousContent: Content, status: OnChangeStatus) => {
    setJsonContent(content);
  }, [setJsonContent]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <JSONEditorReact
          content={jsonContent}
          onChange={handler}
        />
        <div>
          { JSON.stringify(jsonContent) }
        </div>
      </main>
    </>
  )
}
